# Generated by Django 3.2 on 2021-06-09 12:42

import app.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pan_number', models.CharField(max_length=200)),
                ('age', models.IntegerField(validators=[app.validator.validate_age])),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
    ]
